version: "3.1"

services:
    traefik:
        image: traefik:v2.4.8
        container_name: traefik
        ports: 
            - 80:80
            - 443:443
            - 8080:8080
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./conf/traefik.yml:/etc/traefik/traefik.yml
        networks: 
            - traefik-public
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.api.local`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    api:
        build: .
        container_name: api
        volumes: 
            - .:/app
        depends_on: 
            - db
        networks: 
            - database-net
            - traefik-public
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.tls=true"
            - "traefik.http.routers.api.rule=Host(`api.local`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.services.api.loadbalancer.server.port=3001"
            
    db:
        image: mongo:latest
        container_name: mongo_db
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes: 
            - db-data:/data/db
        networks: 
            - database-net
        restart: unless-stopped
        command: mongod
    
    db_admin:
        image: mongo-express:latest
        container_name: mongo_admin
        depends_on: 
            - db
        networks: 
            - database-net
            - traefik-public
        restart: unless-stopped
        environment: 
            - ME_CONFIG_MONGODB_SERVER=db
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mongoadmin.tls=true"
            - "traefik.http.routers.mongoadmin.rule=Host(`mongoadmin.local`)"
            - "traefik.http.routers.mongoadmin.entrypoints=websecure"
            - "traefik.http.services.mongoadmin.loadbalancer.server.port=8081"

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./portainer-data:/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.tls=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
            - "traefik.http.routers.portainer.entrypoints=websecure"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        networks: 
            - traefik-public

volumes: 
    db-data:

networks: 
    database-net:
    traefik-public:
        external: true