api:
  dashboard: true
  insecure: true

log:
  level: "INFO"

providers:
  providersThrottleDuration: 10s
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false
    watch: true
    network: "traefik-public"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "default"
  

certificatesResolvers:
  letsencrypt:
    acme:
      email: "hello@calendink.com"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web